# Generated by Django 5.2.15 on 2026-10-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='avatar_id',
            field=models.CharField(default='cat', help_text='Animal character avatar identifier (cat, dog, panda, rabbit, fox, bear, lion, koala)', max_length=50),
        ),
    ]
